title: Kancelaria Adwokacka Marzena Litewka
description: Profesjonalna pomoc prawna w Krakowie. Prawo cywilne, rodzinne, karne, gospodarcze i inne.
lang: pl
url: "https://mmarzeta.github.io"
email: adwokat@marzena-litewka.pl
